---
name: POE-Component-Client-Whois-Smart
version: 0.07
author:
  - 'Sergey Kotenko <graykot@gmail.com>'
abstract: Provides very quick WHOIS queries with smart features.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Net::Netmask: 0
  POE: 0
  POE::Component::Client::HTTP: 0
  POE::Filter::Line: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
provides:
  POE::Component::Client::Whois::Smart:
    file: lib/POE/Component/Client/Whois/Smart.pm
    version: 0.07
  POE::Component::Client::Whois::Smart::Data:
    file: lib/POE/Component/Client/Whois/Smart/Data.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
